<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6a2b7182-d952-414f-b99c-dc5e8823b513</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Python\PlateGeneration.py" />
    <None Remove="Resources\SQL\AddBatchNodes.sql" />
    <None Remove="Resources\SQL\AddBatchTags.sql" />
    <None Remove="Resources\SQL\AddWaysToMapBatch.sql" />
    <None Remove="Resources\SQL\AddWayToMap.sql" />
    <None Remove="Resources\SQL\GetMapGeojson.sql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.13" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="NetTopologySuite" Version="2.6.0" />
    <PackageReference Include="NetTopologySuite.IO.GeoJSON" Version="4.0.0" />
    <PackageReference Include="NetTopologySuite.IO.GeoJSON4STJ" Version="4.0.0" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="pythonnet" Version="3.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Python\PlateGeneration.py" />
    <EmbeddedResource Include="Resources\SQL\AddBatchNodes.sql" />
    <EmbeddedResource Include="Resources\SQL\AddBatchTags.sql" />
    <EmbeddedResource Include="Resources\SQL\AddWaysToMapBatch.sql" />
    <EmbeddedResource Include="Resources\SQL\AddWayToMap.sql" />
    <EmbeddedResource Include="Resources\SQL\GetMapGeojson.sql" />
  </ItemGroup>

</Project>
